name: Playwright Tests
on:
  push:
    branches: [ main]
jobs:
  playwrightbanktest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 #Checking out repository
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run : |
        echo "Install dependencies"
        npm ci
    - name: Install Playwright Browsers
      run: |
        echo "Install all Playwright Browsers"
        npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        echo "Running Tests, please wait..."
        npx playwright test --workers 1
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
